homepage: "https://accudo.dev"
language: rust
primary_contact: "gerardo@accudo.org"
main_repo: "https://github.com/accudo-labs/accudo-core"
auto_ccs:
  - "oss-fuzz-notifications@accudo.org"
  - "security@accudo.org"
  - "andrea.cappa@accudo.org"
  - "marco.ilardi@accudo.org"
sanitizers:
  - none
fuzzing_engines:
  - libfuzzer
coverage_extra_args: -ignore-filename-regex=.*/rustc/.*