{
 "title": "api",
 "tags": [ "accudo-core" ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Datasource", "query": "prometheus" },
   {
    "name": "metrics_source",
    "query": {
     "query": "label_values(node_process_start_time{}, metrics_source)"
    }
   },
   {
    "name": "chain_name",
    "query": {
     "query": "label_values(node_process_start_time{metrics_source=~\"$metrics_source\"}, chain_name)"
    }
   },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(node_process_start_time{metrics_source=~\"$metrics_source\", chain_name=~\"$chain_name\"}, cluster)"
    }
   },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(node_process_start_time{metrics_source=~\"$metrics_source\", chain_name=~\"$chain_name\", cluster=~\"$cluster\"}, namespace)"
    }
   },
   {
    "name": "kubernetes_pod_name",
    "query": {
     "query": "label_values(node_process_start_time{metrics_source=~\"$metrics_source\", chain_name=~\"$chain_name\", cluster=~\"$cluster\", namespace=~\"$namespace\"}, kubernetes_pod_name)"
    }
   },
   { "name": "endpoint", "query": { "query": "label_values(operation_id)" } },
   { "name": "role", "query": { "query": "label_values(role)" } },
   {
    "name": "interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   { "name": "status", "query": { "query": "label_values(status)" } },
   { "name": "operation_id", "label": "API", "query": { "query": "label_values(operation_id)" } }
  ]
 },
 "panels": [
  {
   "title": "General",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Requests By Response Status Code",
     "type": "timeseries",
     "description": "All requests processed per second, including bad requests",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "targets": [
      {
       "expr": "sum by (status) (rate(accudo_api_response_status_count{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", role=~\"$role\", kubernetes_pod_name=~\"$kubernetes_pod_name\", status=~\"$status\"}[$interval]))",
       "legendFormat": "{{status}}"
      }
     ]
    },
    {
     "title": "Requests by Endpoint",
     "type": "timeseries",
     "description": "Request count by endpoint per $interval",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
     "targets": [
      {
       "expr": "sum by (operation_id) (rate(accudo_api_requests_count{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", role=~\"$role\", kubernetes_pod_name=~\"$kubernetes_pod_name\", status=~\"$status\"}[$interval]))",
       "legendFormat": "{{operation_id}}"
      }
     ]
    },
    {
     "title": "Latency grouped by method",
     "type": "timeseries",
     "description": "Aggregated endpoints latency per $interval, can be filtered by $endpoint",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
     "repeat": "Datasource",
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.50, sum by (method, le) (rate(accudo_api_requests_bucket{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", method=\"GET\"}[$interval])))",
       "legendFormat": "{{method}}-p50"
      },
      {
       "expr": "histogram_quantile(0.90, sum by (method, le) (rate(accudo_api_requests_bucket{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", method=\"GET\"}[$interval])))",
       "legendFormat": "{{method}}-p90"
      },
      {
       "expr": "histogram_quantile(0.99, sum by (method, le) (rate(accudo_api_requests_bucket{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", method=\"GET\"}[$interval])))",
       "legendFormat": "{{method}}-p99"
      },
      {
       "expr": "histogram_quantile(0.50, sum by (method, le) (rate(accudo_api_requests_bucket{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", method=\"POST\"}[$interval])))",
       "legendFormat": "{{method}}-p50"
      },
      {
       "expr": "histogram_quantile(0.90, sum by (method, le) (rate(accudo_api_requests_bucket{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", method=\"POST\"}[$interval])))",
       "legendFormat": "{{method}}-p90"
      },
      {
       "expr": "histogram_quantile(0.99, sum by (method, le) (rate(accudo_api_requests_bucket{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", method=\"POST\"}[$interval])))",
       "legendFormat": "{{method}}-p99"
      }
     ]
    },
    {
     "title": "Counts by method",
     "type": "timeseries",
     "description": "Aggregated endpoints latency per $interval, can be filtered by $endpoint",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by (method, le) (rate(accudo_api_requests_count{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", method=\"GET\"}[$interval]))",
       "legendFormat": "{{method}}-Total"
      },
      {
       "expr": "sum by (method, le) (rate(accudo_api_requests_count{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", method=\"POST\"}[$interval]))",
       "legendFormat": "{{method}}-Total"
      },
      {
       "expr": "sum by (method, le) (rate(accudo_api_requests_count{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", method=\"GET\", status=~\"2.*\"}[$interval]))",
       "legendFormat": "{{method}}-200s"
      },
      {
       "expr": "sum by (method, le) (rate(accudo_api_requests_count{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", method=\"POST\", status=~\"2.*\"}[$interval]))",
       "legendFormat": "{{method}}-200s"
      },
      {
       "expr": "sum by (method, le) (rate(accudo_api_requests_count{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", method=\"GET\", status=~\"4.*\"}[$interval]))",
       "legendFormat": "{{method}}-400s"
      },
      {
       "expr": "sum by (method, le) (rate(accudo_api_requests_count{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", method=\"POST\", status=~\"4.*\"}[$interval]))",
       "legendFormat": "{{method}}-400s"
      },
      {
       "expr": "sum by (method, le) (rate(accudo_api_requests_count{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", method=\"GET\", status=~\"5.*\"}[$interval]))",
       "legendFormat": "{{method}}-500s"
      },
      {
       "expr": "sum by (method, le) (rate(accudo_api_requests_count{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", method=\"POST\", status=~\"5.*\"}[$interval]))",
       "legendFormat": "{{method}}-500s"
      }
     ]
    },
    {
     "title": "Server Internal Errors",
     "type": "timeseries",
     "description": "Server Internal Errors (response code 500) while processing requests, grouped by endpoints",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
     "targets": [
      {
       "expr": "sum by (operation_id) (rate(accudo_api_requests_count{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", role=~\"$role\", kubernetes_pod_name=~\"$kubernetes_pod_name\", status=\"500\"}[$interval]))"
      }
     ]
    },
    {
     "title": "Error Rate",
     "type": "timeseries",
     "description": "500s over number of requests",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum by (operation_id) (rate(accudo_api_requests_count{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", role=~\"$role\", kubernetes_pod_name=~\"$kubernetes_pod_name\", status=\"500\"}[$interval])) / sum by (operation_id) (rate(accudo_api_requests_count{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", role=~\"$role\", kubernetes_pod_name=~\"$kubernetes_pod_name\"}[$interval]))"
      }
     ]
    },
    {
     "title": "(experimental) Avg handler times",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum by (handler) (rate(accudo_api_handlers_sum{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\"}[$interval])) / sum by (handler) (rate(accudo_api_handlers_count{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\"}[$interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "(experimental) Avg middleware times",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum by (middleware) (rate(accudo_api_middleware_sum{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\"}[$interval])) / sum by (middleware) (rate(accudo_api_middleware_count{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\"}[$interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "(experimental) p99.9 handler vs middleware",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.999, sum by (middleware, le) (rate(accudo_api_middleware_bucket{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", middleware=\"cors\"}[$interval])))",
       "legendFormat": "__auto"
      },
      {
       "expr": "histogram_quantile(0.999, sum by (middleware, le) (rate(accudo_api_middleware_bucket{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", middleware=\"nest\"}[$interval])))",
       "legendFormat": "__auto"
      },
      {
       "expr": "histogram_quantile(0.999, sum by (handler, le) (rate(accudo_api_handlers_bucket{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", handler=\"submit_transaction\"}[$interval])))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "(experimental) post sizes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.999, sum by (operation_id, status, le) (rate(accudo_api_post_body_bytes_bucket{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\"}[$interval])))",
       "legendFormat": "__auto"
      },
      {
       "expr": "histogram_quantile(0.999, sum by (operation_id, status, le) (rate(accudo_api_post_body_bytes_bucket{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\"}[$interval])))",
       "legendFormat": "__auto"
      },
      {
       "expr": "histogram_quantile(0.999, sum by (operation_id, status, le) (rate(accudo_api_post_body_bytes_bucket{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\"}[$interval])))",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  { "title": "Per API", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "$operation_id Latency",
   "type": "timeseries",
   "description": "Aggregated endpoints latency per $interval, can be filtered by $endpoint",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 2 },
   "repeat": "operation_id",
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum by (operation_id, le) (rate(accudo_api_requests_bucket{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", operation_id=~\"$operation_id\"}[$interval])))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.90, sum by (operation_id, le) (rate(accudo_api_requests_bucket{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", operation_id=~\"$operation_id\"}[$interval])))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.99, sum by (operation_id, le) (rate(accudo_api_requests_bucket{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", operation_id=~\"$operation_id\"}[$interval])))",
     "legendFormat": "p99"
    }
   ]
  },
  {
   "title": "$operation_id Call Volume",
   "type": "timeseries",
   "description": "Aggregated endpoints call volume per $interval, can be filtered by $endpoint",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 50 },
   "repeat": "operation_id",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (operation_id, le) (rate(accudo_api_requests_count{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", operation_id=~\"$operation_id\"}[$interval]))",
     "legendFormat": "total"
    },
    {
     "expr": "sum by (operation_id, le) (rate(accudo_api_requests_count{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", operation_id=~\"$operation_id\", status=~\"2.*\"}[$interval]))",
     "legendFormat": "success"
    },
    {
     "expr": "sum by (operation_id, le) (rate(accudo_api_requests_count{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", operation_id=~\"$operation_id\", status!~\"2.*\"}[$interval]))",
     "legendFormat": "error"
    }
   ]
  }
 ]
}